name: Deploy
concurrency:
  group: investment-automation
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup poetry
        run: |
          pip install poetry --upgrade
          poetry install
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install AWS CDK
        run: |
          npm i -g aws-cdk
      - name: Deploy
        run: |
          AWS_ACCOUNT="$AWS_ACCOUNT" \
          AWS_DEFAULT_REGION="$AWS_REGION" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          cdk deploy --require-approval never --verbose